### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by clemaitre58** [Macaulay123/Labs#1]
@Macaulay123  could you make a test (googletest or breakpoint, in order to see if the value of point is correct at this line(after execution of the line))

https://github.com/Macaulay123/Labs/blob/5735311775dde69dd3fa6dbb6541c95e01bb658e/modified_lab3/titanic.cpp#L15

**Comment by SadiqMcA** [comment]
I have just pushed the modification I did to Github

Thank you, sir.


________________________________

**Comment by clemaitre58** [comment]
@Macaulay123 I test your code here : https://github.com/clemaitre58/Labs

The problem when you parse your line in titanic.cpp. I think, you don't use properly the >> operator. Perhaps you need to overload it.
You could also use getline like I propose in my solution.

Best,
Cédric

**Comment by SadiqMcA** [comment]
Alright sir I will do as you say.

Thank you, sir.

________________________________

**Comment by clemaitre58** [comment]
Here an example that you can compile and shows that >> not return a part of a line but the whole line : 
https://gist.github.com/clemaitre58/64b516cfc3364ee88a71ebedb7f8b13a

So you need to overload the operator>>

**Comment by clemaitre58** [comment]
@Macaulay123 I add a revision with operator>> overload : https://gist.github.com/clemaitre58/64b516cfc3364ee88a71ebedb7f8b13a
